apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-network-policy
  namespace: hipster
spec:
  podSelector:
    matchLabels:
      tier: database
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: hipster
      podSelector:
        matchLabels:
          tier: backend
    - podSelector:
        matchLabels:
          tier: job
    ports:
    - protocol: TCP
      port: 27017      
  