apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespaces.backend }}
  name: emailservice
  labels:
    app: emailservice
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
  - name: http
    port: {{ .Values.global.ports.emailservice }}
    targetPort: {{ .Values.global.ports.emailservice }}
