apiVersion: v1
kind: Namespace
metadata:
  name: hipster-frontend
  labels:
    name: hipster-frontend

---
apiVersion: v1
kind: Namespace
metadata:
  name: hipster-backend
  labels:
    name: hipster-backend

---
apiVersion: v1
kind: Namespace
metadata:
  name: hipster-database
  labels:
    name: hipster-database
