apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.checkoutservice.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.checkoutservice.name }}
spec:
  replicas: {{ .Values.checkoutservice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.checkoutservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.checkoutservice.name }}
        app.kubernetes.io/name: hipster-shop
        app.kubernetes.io/component: checkout-service
    spec:
      terminationGracePeriodSeconds: {{ .Values.checkoutservice.terminationGracePeriodSeconds }}
      containers:
        - name: server
          image: {{ .Values.checkoutservice.image }}
          imagePullPolicy: {{ .Values.checkoutservice.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.checkoutservice.port }}

          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.name }}

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: service-ports
                  key: CHECKOUTSERVICE_PORT
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: service-addresses
                  key: PRODUCT_CATALOG_SERVICE_ADDR
            - name: SHIPPING_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: service-addresses
                  key: SHIPPING_SERVICE_ADDR
            - name: PAYMENT_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: service-addresses
                  key: PAYMENT_SERVICE_ADDR
            - name: EMAIL_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: service-addresses
                  key: EMAIL_SERVICE_ADDR
            - name: CURRENCY_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: service-addresses
                  key: CURRENCY_SERVICE_ADDR
            - name: CART_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: service-addresses
                  key: CART_SERVICE_ADDR
            - name: ORDER_MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-users
                  key: ORDER_MONGO_USERNAME
            - name: ORDER_MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-users
                  key: ORDER_MONGO_PASSWORD
            - name: ORDER_MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: ORDER_MONGO_URI
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: ORDER_DB_NAME
            - name: MONGO_ORDERS_COLLECTION
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: ORDER_ORDERS_COLLECTION
            - name: MONGO_ORDER_EVENTS_COLLECTION
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: ORDER_EVENTS_COLLECTION

          readinessProbe:
            initialDelaySeconds: {{ .Values.checkoutservice.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.checkoutservice.healthcheck.periodSeconds }}
            timeoutSeconds: {{ .Values.checkoutservice.healthcheck.timeoutSeconds }}
            httpGet:
              path: {{ .Values.checkoutservice.healthcheck.path }}
              port: {{ .Values.checkoutservice.port }}

          livenessProbe:
            initialDelaySeconds: {{ .Values.checkoutservice.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.checkoutservice.healthcheck.periodSeconds }}
            timeoutSeconds: {{ .Values.checkoutservice.healthcheck.timeoutSeconds }}
            httpGet:
              path: {{ .Values.checkoutservice.healthcheck.path }}
              port: {{ .Values.checkoutservice.port }}

          resources:
            requests:
              cpu: {{ .Values.checkoutservice.resources.requests.cpu }}
              memory: {{ .Values.checkoutservice.resources.requests.memory }}
            limits:
              cpu: {{ .Values.checkoutservice.resources.limits.cpu }}
              memory: {{ .Values.checkoutservice.resources.limits.memory }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.checkoutservice.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.checkoutservice.name }}
spec:
  type: {{ .Values.checkoutservice.service.type }}
  selector:
    app: {{ .Values.checkoutservice.name }}
  ports:
    - name: http
      port: {{ .Values.checkoutservice.service.port }}
      targetPort: {{ .Values.checkoutservice.port }}

