{{- if .Values.pv.enabled }}
{{- range $i := until (.Values.mongodb.replicas | int) }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ $.Values.mongodb.name }}-pv-{{ $i }}
  labels:
    app: {{ $.Values.mongodb.name }}
spec:
  capacity:
    storage: {{ $.Values.mongodb.storage }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $.Values.mongodb.storageClass }}
  persistentVolumeReclaimPolicy: {{ $.Values.pv.reclaimPolicy }}
  hostPath:
    path: {{ $.Values.pv.basePath }}/{{ $.Values.mongodb.name }}-{{ $i }}
    type: DirectoryOrCreate
{{- end }}
{{- end }}
