apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.routes.ad.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.adservice.name }}
    app.kubernetes.io/name: hipster-shop
    app.kubernetes.io/component: route
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}

  rules:
    - matches:
        - path:
            type: Exact
            value: {{ .Values.routes.ad.path }}

      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: {{ .Values.routes.ad.rewrite }}

      backendRefs:
        - name: {{ .Values.adservice.name }}
          port: {{ .Values.adservice.service.port }}

