apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      containers:
        - name: server
          image: {{ .Values.frontend.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.frontend.port }}

          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.name }}

          env:
            - name: PORT
              value: "{{ .Values.frontend.port }}"

            - name: GATEWAY_ADDR
              value: "{{ .Values.frontend.gatewayAddr }}"

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.frontend.jwt.secretName }}
                  key: {{ .Values.frontend.jwt.secretKey }}

          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: {{ .Values.frontend.port }}
              httpHeaders:
                - name: "Cookie"
                  value: "shop_session-id=x-readiness-probe"

          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: {{ .Values.frontend.port }}
              httpHeaders:
                - name: "Cookie"
                  value: "shop_session-id=x-liveness-probe"

          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu }}
              memory: {{ .Values.frontend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu }}
              memory: {{ .Values.frontend.resources.limits.memory }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.frontend.name }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.port }}

