---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: hipster
  name: mongo-pv-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mongo-0
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: hipster
  name: mongo-pv-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mongo-1
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: hipster
  name: mongo-pv-2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mongo-2
    type: DirectoryOrCreate
