apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.routes.frontend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.frontend.name }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}

  rules:
    {{- range .Values.routes.frontend.rules }}
    - matches:
        - path:
            type: {{ .type }}
            value: {{ .path }}

      backendRefs:
        - name: {{ $.Values.frontend.name }}
          port: {{ $.Values.frontend.service.port }}
    {{- end }}


