apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gemini.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{ .Values.gemini.secretKey }}: {{ .Values.gemini.apiKey | quote }}

