apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespaces.backend }}
  name: shippingservice
  labels:
    app: shippingservice
spec:
  type: ClusterIP
  selector:
    app: shippingservice
  ports:
  - name: http
    port: {{ .Values.global.ports.shippingservice }}
    targetPort: {{ .Values.global.ports.shippingservice }}
