# ─────────────────────────────────────────────────────────────
#  emailservice — self-contained values
# ─────────────────────────────────────────────────────────────

global:
  namespaces:
    backend: hipster-backend

  images:
    emailservice: "cazzzzz/hipstershop-emailservice:latest"   # CI overwrites the tag

  replicas:
    emailservice: 1

  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

  ports:
    emailservice: 8080

  resources:
    standard:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
