apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  labels:
    app: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
        - name: server
          image: cazzzzz/trf-checkoutservice-hipster:latest
          ports:
          - containerPort: 5050
          readinessProbe:
            httpGet:
              path: "/_healthz"
              port: 5050
          livenessProbe:
            httpGet:
              path: "/_healthz"
              port: 5050
          env:
          - name: ENABLE_TRACING
            value: "1"
          - name: COLLECTOR_SERVICE_ADDR
            value: "jaeger.observability.svc.cluster.local:4317"
          - name: PORT
            value: "5050"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice:3550"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice:50051"
          - name: PAYMENT_SERVICE_ADDR
            value: "paymentservice:50051"
          - name: EMAIL_SERVICE_ADDR
            value: "emailservice:8080"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice:7000"
          - name: CART_SERVICE_ADDR
            value: "cartservice:7070"
          - name: ORDER_MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-app-secret
                key: ORDER_MONGO_USERNAME
          - name: ORDER_MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-app-secret
                key: ORDER_MONGO_PASSWORD
          - name: ORDER_MONGO_URI
            value: "mongodb://$(ORDER_MONGO_USERNAME):$(ORDER_MONGO_PASSWORD)@mongodb-0.mongo-headless:27017,mongodb-1.mongo-headless:27017,mongodb-2.mongo-headless:27017/order_db?replicaSet=rs0&authSource=order_db&authMechanism=SCRAM-SHA-256"
          - name: MONGO_DATABASE
            value: "order_db"
          - name: MONGO_ORDERS_COLLECTION
            value: "orders"
          - name: MONGO_ORDER_EVENTS_COLLECTION
            value: "order_events"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  labels:
    app: checkoutservice
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
  - name: http
    port: 5050
    targetPort: 5050
