apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  labels:
    app: emailservice
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: cazzzzz/trf-emailservice-hipster:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENABLE_TRACING
          value: "1"
        - name: COLLECTOR_SERVICE_ADDR
          value: "jaeger.observability.svc.cluster.local:4317"
        - name: PORT
          value: "8080"
        - name: EMAIL_MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-app-secret
              key: NOTIFICATION_MONGO_USERNAME
        - name: EMAIL_MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-app-secret
              key: NOTIFICATION_MONGO_PASSWORD
        - name: EMAIL_MONGO_URI
          value: "mongodb://$(EMAIL_MONGO_USERNAME):$(EMAIL_MONGO_PASSWORD)@mongodb-0.mongo-headless.hipster.svc.cluster.local:27017,mongodb-1.mongo-headless.hipster.svc.cluster.local:27017,mongodb-2.mongo-headless.hipster.svc.cluster.local:27017/notification_db?replicaSet=rs0&authSource=notification_db&authMechanism=SCRAM-SHA-256"
        - name: MONGO_DATABASE
          value: "notification_db"
        - name: MONGO_EMAIL_EVENTS_COLLECTION
          value: "email_events"
        readinessProbe:
          periodSeconds: 5
          httpGet:
            path: "/_healthz"
            port: 8080
        livenessProbe:
          periodSeconds: 5
          httpGet:
            path: "/_healthz"
            port: 8080
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  labels:
    app: emailservice
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
  - name: http
    port: 8080
    targetPort: 8080
