apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hipster
resources:
 - namespace.yaml
 - pv.yaml
 - secrets.yaml
 - mongodb.yaml
 - adservice.yaml
 - authservice.yaml
 - cartservice.yaml
 - checkoutservice.yaml
 - currencyservice.yaml
 - emailservice.yaml
 - paymentservice.yaml
 - productcatalogservice.yaml
 - recommendationservice.yaml
 - shippingservice.yaml
 - frontend.yaml
 - kgateway.yaml
