apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: cazzzzz/trf-paymentservice-hipster:latest
        ports:
        - containerPort: 50051
        env:
        - name: ENABLE_TRACING
          value: "1"
        - name: COLLECTOR_SERVICE_ADDR
          value: "jaeger.observability.svc.cluster.local:4317"
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
        - name: PAYMENT_MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-app-secret
              key: PAYMENT_MONGO_USERNAME
        - name: PAYMENT_MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-app-secret
              key: PAYMENT_MONGO_PASSWORD
        - name: PAYMENT_MONGO_URI
          value: "mongodb://$(PAYMENT_MONGO_USERNAME):$(PAYMENT_MONGO_PASSWORD)@mongodb-0.mongo-headless.hipster.svc.cluster.local:27017,mongodb-1.mongo-headless.hipster.svc.cluster.local:27017,mongodb-2.mongo-headless.hipster.svc.cluster.local:27017/payment_db?replicaSet=rs0&authSource=payment_db&authMechanism=SCRAM-SHA-256"
        - name: MONGO_DATABASE
          value: "payment_db"
        - name: MONGO_PAYMENTS_COLLECTION
          value: "charges"
        readinessProbe:
          httpGet:
            path: "/_healthz"
            port: 50051
        livenessProbe:
          httpGet:
            path: "/_healthz"
            port: 50051
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  type: ClusterIP
  selector:
    app: paymentservice
  ports:
  - name: http
    port: 50051
    targetPort: 50051
