apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  labels:
    app: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: cazzzzz/trf-productcatalogservice-hipster:latest
        ports:
        - containerPort: 3550
        env:
        - name: ENABLE_TRACING
          value: "1"
        - name: COLLECTOR_SERVICE_ADDR
          value: "jaeger.observability.svc.cluster.local:4317"
        - name: PORT
          value: "3550"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-app-secret
              key: CATALOG_MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-app-secret
              key: CATALOG_MONGO_PASSWORD
        - name: MONGO_DATABASE
          value: "catalog_db"
        - name: MONGO_PRODUCTS_COLLECTION
          value: "products"
        - name: PRODUCTS_FALLBACK_LOCAL
          value: "true"
        - name: MONGO_URI
          value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb-0.mongo-headless.hipster.svc.cluster.local:27017,mongodb-1.mongo-headless.hipster.svc.cluster.local:27017,mongodb-2.mongo-headless.hipster.svc.cluster.local:27017/catalog_db?replicaSet=rs0&authSource=catalog_db&authMechanism=SCRAM-SHA-256"
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          httpGet:
            path: "/_healthz"
            port: 3550
        livenessProbe:
          initialDelaySeconds: 40
          failureThreshold: 6
          periodSeconds: 5
          httpGet:
            path: "/_healthz"
            port: 3550
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  labels:
    app: productcatalogservice
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
  ports:
  - name: http
    port: 3550
    targetPort: 3550
