apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  labels:
    app: recommendationservice
spec:
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: cazzzzz/trf-recommendationservice-hipster:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          httpGet:
            path: "/_healthz"
            port: 8080
        livenessProbe:
          periodSeconds: 5
          httpGet:
            path: "/_healthz"
            port: 8080
        env:
        - name: ENABLE_TRACING
          value: "1"
        - name: COLLECTOR_SERVICE_ADDR
          value: "jaeger.observability.svc.cluster.local:4317"
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        - name: ANALYTICS_MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-app-secret
              key: ANALYTICS_MONGO_USERNAME
        - name: ANALYTICS_MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-app-secret
              key: ANALYTICS_MONGO_PASSWORD
        - name: ANALYTICS_MONGO_URI
          value: "mongodb://$(ANALYTICS_MONGO_USERNAME):$(ANALYTICS_MONGO_PASSWORD)@mongodb-0.mongo-headless:27017,mongodb-1.mongo-headless:27017,mongodb-2.mongo-headless:27017/analytics_db?replicaSet=rs0&authSource=analytics_db&authMechanism=SCRAM-SHA-256"
        - name: MONGO_DATABASE
          value: "analytics_db"
        - name: MONGO_RECOMMENDATIONS_COLLECTION
          value: "recommendations"
        resources:
          requests:
            cpu: 100m
            memory: 220Mi
          limits:
            cpu: 200m
            memory: 450Mi
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  labels:
    app: recommendationservice
spec:
  type: ClusterIP
  selector:
    app: recommendationservice
  ports:
  - name: http
    port: 8080
    targetPort: 8080
