apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hipstershop.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: {{ .Values.hpa.frontend.minReplicas }}
  maxReplicas: {{ .Values.hpa.frontend.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.frontend.cpuUtilization }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.frontend.memoryUtilization }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.hpa.frontend.scaleDown.stabilizationWindowSeconds }}
      policies:
      - type: Percent
        value: {{ .Values.hpa.frontend.scaleDown.percentValue }}
        periodSeconds: {{ .Values.hpa.frontend.scaleDown.periodSeconds }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.hpa.frontend.scaleUp.stabilizationWindowSeconds }}
      policies:
      - type: Percent
        value: {{ .Values.hpa.frontend.scaleUp.percentValue }}
        periodSeconds: {{ .Values.hpa.frontend.scaleUp.periodSeconds }}
      - type: Pods
        value: {{ .Values.hpa.frontend.scaleUp.podsValue }}
        periodSeconds: {{ .Values.hpa.frontend.scaleUp.periodSeconds }}
      selectPolicy: Max
