apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespaces.backend }}
  name: recommendationservice
  labels:
    app: recommendationservice
spec:
  type: ClusterIP
  selector:
    app: recommendationservice
  ports:
  - name: http
    port: {{ .Values.global.ports.recommendationservice }}
    targetPort: {{ .Values.global.ports.recommendationservice }}
