apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespaces.backend }}
  name: productcatalogservice
  labels:
    app: productcatalogservice
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
  ports:
  - name: http
    port: {{ .Values.global.ports.productcatalogservice }}
    targetPort: {{ .Values.global.ports.productcatalogservice }}
