apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespaces.backend }}
  name: currencyservice
  labels:
    app: currencyservice
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
  - name: http
    port: {{ .Values.global.ports.currencyservice }}
    targetPort: {{ .Values.global.ports.currencyservice }}
