# ─────────────────────────────────────────────────────────────
#  currencyservice — self-contained values
# ─────────────────────────────────────────────────────────────

global:
  namespaces:
    backend: hipster-backend

  images:
    currencyservice: "cazzzzz/hipstershop-currencyservice:latest"   # CI overwrites the tag

  replicas:
    currencyservice: 1

  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

  ports:
    currencyservice: 7000

  resources:
    standard:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
