apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespaces.database }}
  labels:
    name: {{ .Values.global.namespaces.database }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: mongodb
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    helm.sh/resource-policy: keep
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-root
  namespace: {{ .Values.global.namespaces.database }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: mongodb
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: {{ .Values.global.mongodb.rootUsername | quote }}
  MONGO_ROOT_PASSWORD: {{ .Values.global.mongodb.rootPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-users
  namespace: {{ .Values.global.namespaces.database }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: mongodb
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  AUTH_MONGO_USERNAME: {{ .Values.global.mongodb.users.auth.username | quote }}
  AUTH_MONGO_PASSWORD: {{ .Values.global.mongodb.users.auth.password | quote }}
  CART_MONGO_USERNAME: {{ .Values.global.mongodb.users.cart.username | quote }}
  CART_MONGO_PASSWORD: {{ .Values.global.mongodb.users.cart.password | quote }}
  CATALOG_MONGO_USERNAME: {{ .Values.global.mongodb.users.catalog.username | quote }}
  CATALOG_MONGO_PASSWORD: {{ .Values.global.mongodb.users.catalog.password | quote }}
  ORDER_MONGO_USERNAME: {{ .Values.global.mongodb.users.order.username | quote }}
  ORDER_MONGO_PASSWORD: {{ .Values.global.mongodb.users.order.password | quote }}
  PAYMENT_MONGO_USERNAME: {{ .Values.global.mongodb.users.payment.username | quote }}
  PAYMENT_MONGO_PASSWORD: {{ .Values.global.mongodb.users.payment.password | quote }}
  NOTIFICATION_MONGO_USERNAME: {{ .Values.global.mongodb.users.notification.username | quote }}
  NOTIFICATION_MONGO_PASSWORD: {{ .Values.global.mongodb.users.notification.password | quote }}
  ANALYTICS_MONGO_USERNAME: {{ .Values.global.mongodb.users.analytics.username | quote }}
  ANALYTICS_MONGO_PASSWORD: {{ .Values.global.mongodb.users.analytics.password | quote }}
