apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: {{ .Release.Namespace }}
  labels:
    app: currencyservice
    {{- include "hipstershop.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas.currencyservice }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: {{ .Values.images.currencyservice }}
        ports:
        - name: http
          containerPort: {{ .Values.ports.currencyservice }}
        envFrom:
        - configMapRef:
            name: hipster-config
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: service-ports
              key: CURRENCYSERVICE_PORT
        - name: DISABLE_PROFILER
          valueFrom:
            configMapKeyRef:
              name: app-features
              key: CURRENCY_SERVICE_RANDOM_ERROR
        readinessProbe:
          httpGet:
            path: "/_healthz"
            port: {{ .Values.ports.currencyservice }}
        livenessProbe:
          httpGet:
            path: "/_healthz"
            port: {{ .Values.ports.currencyservice }}
        resources:
          requests:
            cpu: {{ .Values.resources.standard.requests.cpu }}
            memory: {{ .Values.resources.standard.requests.memory }}
          limits:
            cpu: {{ .Values.resources.standard.limits.cpu }}
            memory: {{ .Values.resources.standard.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: {{ .Release.Namespace }}
  labels:
    app: currencyservice
    {{- include "hipstershop.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
  - name: http
    port: {{ .Values.ports.currencyservice }}
    targetPort: {{ .Values.ports.currencyservice }}
