apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: {{ .Release.Namespace }}
  labels:
    app: emailservice
    {{- include "hipstershop.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas.emailservice }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: {{ .Values.images.emailservice }}
        ports:
        - containerPort: {{ .Values.ports.emailservice }}
        envFrom:
        - configMapRef:
            name: hipster-config
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: service-ports
              key: EMAILSERVICE_PORT
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-users
              key: NOTIFICATION_MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-users
              key: NOTIFICATION_MONGO_PASSWORD
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: NOTIFICATION_DB_NAME
        - name: MONGO_EMAIL_EVENTS_COLLECTION
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: NOTIFICATION_EMAIL_EVENTS_COLLECTION
        - name: MONGO_URI
          value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@{{ include "hipstershop.mongoHosts" . }}/{{ .Values.mongodb.users.notification.database }}?replicaSet={{ .Values.mongodb.replicaSetName }}&authSource={{ .Values.mongodb.users.notification.database }}&authMechanism=SCRAM-SHA-256"
        readinessProbe:
          periodSeconds: 5
          httpGet:
            path: "/_healthz"
            port: {{ .Values.ports.emailservice }}
        livenessProbe:
          periodSeconds: 5
          httpGet:
            path: "/_healthz"
            port: {{ .Values.ports.emailservice }}
        resources:
          requests:
            cpu: {{ .Values.resources.standard.requests.cpu }}
            memory: {{ .Values.resources.standard.requests.memory }}
          limits:
            cpu: {{ .Values.resources.standard.limits.cpu }}
            memory: {{ .Values.resources.standard.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: {{ .Release.Namespace }}
  labels:
    app: emailservice
    {{- include "hipstershop.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
  - name: http
    port: {{ .Values.ports.emailservice }}
    targetPort: {{ .Values.ports.emailservice }}
