apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
    {{- include "hipstershop.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas.frontend }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: server
        image: {{ .Values.images.frontend }}
        ports:
        - containerPort: {{ .Values.ports.frontend }}
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/_healthz"
            port: {{ .Values.ports.frontend }}
            httpHeaders:
            - name: "Cookie"
              value: "shop_session-id=x-readiness-probe"
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/_healthz"
            port: {{ .Values.ports.frontend }}
            httpHeaders:
            - name: "Cookie"
              value: "shop_session-id=x-liveness-probe"
        envFrom:
        - configMapRef:
            name: hipster-config
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: service-ports
              key: FRONTEND_PORT
        - name: GATEWAY_ADDR
          valueFrom:
            configMapKeyRef:
              name: service-addresses
              key: GATEWAY_ADDR
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        resources:
          requests:
            cpu: {{ .Values.resources.standard.requests.cpu }}
            memory: {{ .Values.resources.standard.requests.memory }}
          limits:
            cpu: {{ .Values.resources.standard.limits.cpu }}
            memory: {{ .Values.resources.standard.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
    {{- include "hipstershop.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: {{ .Values.ports.frontendSvc }}
    targetPort: {{ .Values.ports.frontend }}
