apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  namespace: {{ .Release.Namespace }}
  labels:
    app: recommendationservice
    {{- include "hipstershop.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas.recommendationservice }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: {{ .Values.images.recommendationservice }}
        ports:
        - containerPort: {{ .Values.ports.recommendationservice }}
        readinessProbe:
          periodSeconds: 5
          httpGet:
            path: "/_healthz"
            port: {{ .Values.ports.recommendationservice }}
        livenessProbe:
          periodSeconds: 5
          httpGet:
            path: "/_healthz"
            port: {{ .Values.ports.recommendationservice }}
        envFrom:
        - configMapRef:
            name: hipster-config
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: service-ports
              key: RECOMMENDATIONSERVICE_PORT
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: service-addresses
              key: PRODUCT_CATALOG_SERVICE_ADDR
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-users
              key: ANALYTICS_MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-users
              key: ANALYTICS_MONGO_PASSWORD
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: ANALYTICS_DB_NAME
        - name: MONGO_RECOMMENDATIONS_COLLECTION
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: ANALYTICS_RECOMMENDATIONS_COLLECTION
        - name: MONGO_URI
          value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@{{ include "hipstershop.mongoHosts" . }}/{{ .Values.mongodb.users.analytics.database }}?replicaSet={{ .Values.mongodb.replicaSetName }}&authSource={{ .Values.mongodb.users.analytics.database }}&authMechanism=SCRAM-SHA-256"
        resources:
          requests:
            cpu: {{ .Values.resources.recommendation.requests.cpu }}
            memory: {{ .Values.resources.recommendation.requests.memory }}
          limits:
            cpu: {{ .Values.resources.recommendation.limits.cpu }}
            memory: {{ .Values.resources.recommendation.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: {{ .Release.Namespace }}
  labels:
    app: recommendationservice
    {{- include "hipstershop.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: recommendationservice
  ports:
  - name: http
    port: {{ .Values.ports.recommendationservice }}
    targetPort: {{ .Values.ports.recommendationservice }}
