apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: {{ .Release.Namespace }}
  labels:
    app: shippingservice
    {{- include "hipstershop.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas.shippingservice }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: server
        image: {{ .Values.images.shippingservice }}
        ports:
        - containerPort: {{ .Values.ports.shippingservice }}
        envFrom:
        - configMapRef:
            name: hipster-config
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: service-ports
              key: SHIPPINGSERVICE_PORT
        readinessProbe:
          periodSeconds: 5
          httpGet:
            path: "/_healthz"
            port: {{ .Values.ports.shippingservice }}
        livenessProbe:
          httpGet:
            path: "/_healthz"
            port: {{ .Values.ports.shippingservice }}
        resources:
          requests:
            cpu: {{ .Values.resources.standard.requests.cpu }}
            memory: {{ .Values.resources.standard.requests.memory }}
          limits:
            cpu: {{ .Values.resources.standard.limits.cpu }}
            memory: {{ .Values.resources.standard.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: {{ .Release.Namespace }}
  labels:
    app: shippingservice
    {{- include "hipstershop.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: shippingservice
  ports:
  - name: http
    port: {{ .Values.ports.shippingservice }}
    targetPort: {{ .Values.ports.shippingservice }}
