apiVersion: v2
name: hipstershop
description: |
  HipsterShop
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - microservices
  - ecommerce
  - kubernetes
  - mongodb
  - kgateway
maintainers:
  - name: Team 4
home: https://github.com/Yampss/HipsterShop
sources:
  - https://github.com/Yampss/HipsterShop
dependencies: []
