name: cartservice CI

on:
  push:
    branches:
      - feature/ci
    paths:
      - 'src/cartservice/**'
      - '.github/workflows/cartservice.yaml'
      - '.github/workflows/template.yaml'
  pull_request:
    branches:
      - feature/ci
    paths:
      - 'src/cartservice/**'
      - '.github/workflows/cartservice.yaml'
      - '.github/workflows/template.yaml'

jobs:
  call-template:
    uses: ./.github/workflows/template.yaml
    with:
      service_name: cartservice
      service_path: src/cartservice/src
      runtime: dotnet
      dotnet-version: "8.0"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
