name: productcatalogservice CI

on:
  push:
    branches:
      - chore/ci-setup
    paths:
      - 'src/productcatalogservice/**'
      - '.github/workflows/productcatalogservice.yaml'
      - '.github/workflows/template.yaml'
  pull_request:
    branches:
      - chore/ci-setup
    paths:
      - 'src/productcatalogservice/**'
      - '.github/workflows/productcatalogservice.yaml'
      - '.github/workflows/template.yaml'

jobs:
  call-template:
    uses: ./.github/workflows/template.yaml
    with:
      service_name: productcatalogservice
      service_path: src/productcatalogservice
      runtime: go
      go-version: "1.26.1"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
