name: recommendationservice CI

on:
  push:
    branches:
      - ci-v1
    paths:
      - 'src/recommendationservice/**'
      - '.github/workflows/recommendationservice.yaml'
      - '.github/workflows/template.yaml'
  pull_request:
    branches:
      - ci-v1
    paths:
      - 'src/recommendationservice/**'
      - '.github/workflows/recommendationservice.yaml'
      - '.github/workflows/template.yaml'

jobs:
  call-template:
    uses: ./.github/workflows/template.yaml
    with:
      service_name: recommendationservice
      service_path: src/recommendationservice
      runtime: python
      python-version: "3.11"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
